bonsai-rx/harp

Bonsai.Harp.Tests/TestHarpMessage.cs
Bonsai.Harp/Format.cs
Bonsai.Harp/HarpCommand.cs
Bonsai.Harp/HarpMessage.cs

This PR fixes a number of issues relating to the creation of Harp messages from payload data. Regression tests are included for all functionality.
Fixes #13 
Fixes #14 
Fixes #15 
Fixes #16

Fix and extend support for creating Harp messages from payload data

---

Bonsai.Harp.Design/Bonsai.Harp.Design.csproj
Bonsai.Harp.Design/DeviceConfigurationDialog.cs
Bonsai.Harp.Design/DeviceConfigurationEditor.cs
Bonsai.Harp.Tests/Bonsai.Harp.Tests.csproj
Bonsai.Harp/Bonsai.Harp.csproj

This PR adds support for multi-targeting .NET standard against the latest `Bonsai.Core`.
Fixes #17

Add netstandard build target for core assembly

---

Bonsai.Harp/CreateTimestamped.cs

This PR introduces a new operator for creating timestamped payload objects for arbitrary types from an existing timestamp or Harp message. This is useful when designing systems that require assigning Harp timestamps to non-Harp events for logging purposes.
Fixes #26

Add operator for creating timestamped values

---

Bonsai.Harp.Design/DeviceConfiguration.cs
Bonsai.Harp.Design/DeviceConfigurationDialog.Designer.cs
Bonsai.Harp.Design/DeviceConfigurationDialog.cs
Bonsai.Harp.Design/DeviceConfigurationDialog.resx
Bonsai.Harp.Design/Properties/Resources.Designer.cs
Bonsai.Harp.Design/Properties/Resources.resx
Bonsai.Harp/Bootloader.cs
Bonsai.Harp/FirmwareMetadata.cs

This PR rounds-up the new device configuration dialog with a port name selection drop-down to allow inspecting information from different devices and an improved bootloader for updating device firmware.
Fixes #31

Improve device configuration dialog and firmware bootloader

---

Bonsai.Harp/AsyncDevice.cs

This PR adds new overloads to the `AsyncDevice` class to support reading config registers with array payloads.
Fixes #38

Add missing array overloads for ReadAsync

---

Bonsai.Harp/AsyncDevice.cs

This PR adds missing async methods for reading device metadata registers, specifically:
- WhoAmI
- AssemblyVersion
- CoreVersion
- SerialNumber
Fixes #42

Add missing metadata read methods to async API

---

Bonsai.Harp/Constants.cs
Bonsai.Harp/Device.cs

This PR resolves issues with the `Device` base class to improve behavior of derived classes with respect to XML serialization and editor naming. The XML namespace is now fixed to `Bonsai.Harp` and the default value is used when implementing `INamedElement` to allow default device name to match the derived class name.
Fixes #44 
Fixes #41

Resolve issues with Device base class XML namespace and default editor name

---

Bonsai.Harp/Bootloader.cs

This PR adds a timeout when reading the reset register to allow forced updates to escape directly into bootloader mode. This will allow devices which are locked in bootloader mode to be flashed using the device setup editor.
Fixes #47

Allow forced updates to escape to bootloader mode

---

Bonsai.Harp.Tests/TestFirmwareMetadata.cs
Bonsai.Harp/Bonsai.Harp.csproj
Bonsai.Harp/CommandBuilder.cs
Bonsai.Harp/CreateMessage.cs
Bonsai.Harp/CreateMessageBuilder.cs
Bonsai.Harp/Device.Generated.cs
Bonsai.Harp/EventBuilder.cs
Bonsai.Harp/FilterMessage.cs
Bonsai.Harp/FilterMessageBuilder.cs
Bonsai.Harp/Format.cs
Bonsai.Harp/FormatBuilder.cs
Bonsai.Harp/HarpCombinatorBuilder.cs
Bonsai.Harp/Parse.cs
Bonsai.Harp/ParseBuilder.cs

This PR refactors the core Harp message manipulation operators to avoid having custom logic in generated register types. The goal is to improve the library robustness to future redesign, since all that the custom device packages really need to provide is the specific logic for parsing or formatting message payloads.

Refactor core operators to pull logic out of generated register types

---

Bonsai.Harp/Bonsai.Harp.csproj
Bonsai.Harp/MessageWriter.cs

This PR introduces a new operator for logging Harp messages. The first implementation of the `MessageWriter` operator simply writes the raw message bytes into the specified stream, but pending resolution of https://github.com/bonsai-rx/bonsai/issues/1309 this could be easily generalized to support writing one binary stream per register when receiving a stream of grouped observables.
Fixes #25

Add specialized operator for logging Harp messages

---

Bonsai.Harp/ConvertTimestamped.cs

This PR introduces a new operator `ConvertTimestamped` that aims to make it easier to manipulate and transform Harp timestamped values.
This is a nested operator which extracts the value from a `Timestamped<T>` input; applies the custom specified conversion operation in the nested workflow; and reassembles a timestamped sequence where all values resulting from the transformation are matched with the timestamps from the original sequence.

Support timestamp preserving payload conversions

---

Bonsai.Harp/Device.cs

This PR removes the behavior of writing information to the standard output when the `PortName` property changes. To keep backwards-compatibility the behavior is kept when the device identifier (`whoAmI`) is left with its default value of zero. This is the case when using the debug `Device` class.
Updating the name of the device dynamically is not so important when using a well-defined high-level interface, since the device node will always display the name of the device anyway, and other information can be found in the default editor dialog.
Fixes #22

Avoid console writes when device ID is specified

---

Bonsai.Harp/AsyncDevice.cs
Bonsai.Harp/Bootloader.cs
Bonsai.Harp/Device.cs
Bonsai.Harp/TaskExtensions.cs

This PR verifies the device identifier and firmware version registers against specified metadata. The checks are performed asynchronously at device initialization time, and any pending invalid messages in the serial port buffer are flushed.
Even if no device-specific metadata is provided, the implementation will attempt to perform a register read command on the [WHO_AM_I](https://harp-tech.org/About/How-HARP-works/common_registers_operation_devices.html#r-who-am-i-who-am-i) register with a 500 ms timeout. This ensures that the device on the other side of the serial port can at least implement a simple register exchange following the Harp protocol.
Fixes #20 
Fixes #53

Assert identifier and firmware version

---

Bonsai.Harp/CreateMessage.cs
Bonsai.Harp/CreateMessageBuilder.cs
Bonsai.Harp/CreateTimestamped.cs
Bonsai.Harp/Device.Generated.cs
Bonsai.Harp/DeviceCommand.cs
Bonsai.Harp/Format.cs
Bonsai.Harp/FormatBuilder.cs
Bonsai.Harp/HarpMessage.cs
Bonsai.Harp/OffsetTimestamp.cs
Bonsai.Harp/SynchronizeTimestamp.cs
Directory.Build.props

This PR rewrites the interface of the core `Format` and `CreateMessage` polymorphic operators to make it easier to modify and inject custom timestamps into all created messages. For the `CreateMessage` polymorphic types, it assumes a structure of both non-timestamped and timestamped types, mirroring the one in use for registers, that indicates whether payloads are intended to be created with a timestamp.
The flexibility of `Format` has also been improved to allow modifying and reshaping every available general attribute of Harp messages, including address, message type, payload type and timestamp. This makes it possible to edit streams of messages in a much more general way.
New overloads for `CreateTimestamped` and a new operator `OffsetTimestamp` have been introduced to make it easier …

Improve support for timestamped payload manipulation

---

Bonsai.Harp/OffsetTimestamp.cs

This PR avoids a round-trip conversion between `TimeSpan` and `double` which was causing loss of precision due to limitations on the `TimeSpan.FromSeconds` method which is truncated to millisecond. The `TimeShift` property was also made non-nullable since a time span already has a zero default.

Avoid nullable and round-trip double conversions

---

Bonsai.Harp/AsyncDevice.cs
Bonsai.Harp/Device.cs

This PR introduces support for cancellation in all async register access methods in the `AsyncDevice` class. This allows for generalized support for cancellation in case devices are unresponsive, and it also lays the foundation for supporting cancellation of scheduled async operations in future iterations.
Fixes #62

Add cancellation support to core async API

---

Bonsai.Harp/AsyncDevice.cs
Bonsai.Harp/BufferedStream.cs
Bonsai.Harp/Device.cs
Bonsai.Harp/FileDevice.cs
Bonsai.Harp/SerialTransport.cs
Bonsai.Harp/StreamTransport.cs

Following on developments from https://github.com/bonsai-rx/bonsai/pull/1444 this PR refactors the serial transport layer to avoid event callbacks. This has the advantage of both eliminating dispose deadlocks and making all Harp interfaces compatible with Mono, e.g. for running on Linux desktop, Raspberry Pi, Unity3D, etc.
Fixes #62

Refactor serial transport to avoid event callbacks

---

Directory.Build.props
LICENSE

With this new release we are updating our copyright statements and contribution guidelines to reflect the creation of the [Bonsai Foundation CIC](https://bonsai-rx.org/foundation/).
The role of the Bonsai Foundation is to organize the development of the Bonsai ecosystem, establish clear contribution guidelines, administer and moderate the code repositories and user forums, and develop and improve access to freely available teaching materials, documentation, and community projects. We want to support our growing community to learn, teach, and contribute to Bonsai more effectively so we can empower more scientists all over the world to develop their own experiments using visual reactive programming.
You can read more about the Foundation and our [Community Interest …

Update copyright notice

---

Bonsai.Harp.Visualizers/Bonsai.Harp.Visualizers.csproj
Bonsai.Harp.Visualizers/BoundedPointPairList.cs
Bonsai.Harp.Visualizers/GraphHelper.cs
Bonsai.Harp.Visualizers/Properties/AssemblyInfo.cs
Bonsai.Harp.Visualizers/Properties/launchSettings.json
Bonsai.Harp.Visualizers/QueueList.cs
Bonsai.Harp.Visualizers/TimelineGraph.cs
Bonsai.Harp.Visualizers/TimelineGraphBuilder.cs
Bonsai.Harp.Visualizers/TimelineGraphView.Designer.cs
Bonsai.Harp.Visualizers/TimelineGraphView.cs
Bonsai.Harp.Visualizers/TimelineGraphView.resx
Bonsai.Harp.Visualizers/TimelineGraphVisualizer.cs
Bonsai.Harp.Visualizers/ToolStripEditableLabel.cs
Bonsai.Harp.sln

This PR adds a new visualizer for synchronized Harp message streams. It takes a grouped or ungrouped stream of messages and plots every message as a point, where the X-coordinate is taken from the message timestamp along a shared time axis, and the Y-coordinate is the message register address.
The `TimeSpan` property can be optionally specified to restrict the number of plotted messages to a specific interval. In this case, the most recent messages are always taken, and messages older than the specified time span from the most recent message timestamp will be discarded.
The new `TimelineGraph` operator is introduced as a new package `Bonsai.Harp.Visualizers`.

Add timeline visualizer for Harp message streams

---

Bonsai.Harp/Bonsai.Harp.csproj
Bonsai.Harp/Device.cs

At shutdown, the device should usually be sent into `Standby` mode before closing the serial connection. However, if this transmission fails due to IO issues (e.g. a cable has been disconnected), we should still make sure we close the connection.

Ensure transport is closed on shutdown IO errors

---

.github/workflows/Bonsai.Harp.yml

The documentation for this repo is published alongside [the main Harp website](https://github.com/harp-tech/harp-tech.github.io), so we don't need a dedicated website for it.
This PR intentionally leaves the docs building job enabled for CI purposes.
The docs deployment step is still able to be used with forks for those working on documentation.

Disable publishing documentation for the canonical repo

---

src/Bonsai.Harp/Device.cs

Transport initialization and disposal are asynchronous and also depend on operator state, which may be shared across parallel subscriptions. To allow dynamic instantiation of transports from a single operator, this state needs to be captured immediately on observable creation and retained as a copy throughout the entire transport lifetime.
As a further note, it is not enough to capture on subscribe, since error handling operators such as `Retry` may inadvertently cause state to be shared, and also the async lambda is not guaranteed to run synchronously even if the first few steps are calls to synchronous methods.
Fixes #96

Capture operation state before transport creation
